#!/usr/bin/env python3
"""Build the importable Shadowrocket configuration deterministically."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "config" / "base.conf"
CUSTOM = ROOT / "rules" / "custom.list"
APPS = ROOT / "rewrites" / "apps.list"
OUTPUT = ROOT / "dist" / "shadowrocket.conf"
MARKERS = {
    "{{CUSTOM_RULES}}": CUSTOM,
    "{{APP_RULES}}": APPS,
}


def read_source(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    if "\r" in text:
        raise ValueError(f"{path.relative_to(ROOT)} must use LF line endings")
    if not text.endswith("\n"):
        raise ValueError(f"{path.relative_to(ROOT)} must end with a newline")
    return text


def render() -> str:
    result = read_source(BASE)
    for marker, source in MARKERS.items():
        if result.count(marker) != 1:
            raise ValueError(f"expected one {marker} marker in {BASE.relative_to(ROOT)}")
        result = result.replace(marker, read_source(source).rstrip("\n"))
    return "# Generated by tools/build.py; edit checked-in sources, not this file.\n" + result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()
    generated = render()

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"build check passed: {OUTPUT.relative_to(ROOT)}")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"built {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
